services:
  deploy-server:
    image: deploy-server
    container_name: dpServer
    build: .
    ports:
      - '8080:8080'
    volumes:
      - /home/jason5/my-page:/home/jason5/my-page
    working_dir: /home/jason5/my-page