services:
  my-page:
    image: mypage
    container_name: c1
    build: .
    ports:
      - '443:443'
    volumes:
      - /etc/letsencrypt/live/mehtab.in/fullchain.pem:/etc/ssl/certs/fullchain.pem  
      - /etc/letsencrypt/live/mehtab.in/privkey.pem:/etc/ssl/private/privkey.pem  
    environment:
      - NODE_ENV=PROD
    restart: unless-stopped